### ISSUE TITLE
Bamboo hitbox is outside of render and collision box

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#33]
Please fix this

**Comment by thedarkcolour** [comment]
Fixed in 0.1.9. Use the latest version

**Comment by futurenp** [comment]
I have installed the latest version and it still appears to be happening... not sure whats going on here.
